apiVersion: apps/v1
kind: Deployment
metadata:
  name: skills-msa1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skills-msa1
  template:
    metadata:
      labels:
        app: skills-msa1
    spec:
      containers:
        - name: skills-ecr
          image: 763789849822.dkr.ecr.ap-northeast-2.amazonaws.com/skills-ecr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
